### ISSUE TITLE
编译有问题

### ISSUE THREAD

**Issue by luciaL** [xiahouzuoxin/caffe_segtask#3]
编译，multi_stage_meanfiled.cpp时报错
在tvg_commom_utils.hpp:错误：‘stof’不是‘std’的成员

**Comment by xiahouzuoxin** [comment]
参考deeplab编译，没有使用cudnn，github上的版本暂时没有merge cuda8.0的支持

**Comment by luciaL** [comment]
要安装matio吗？？？

**Comment by xiahouzuoxin** [comment]
对，代码是从deeplab迁移过来的，我没有从deeplab上去掉这个依赖

**Comment by luciaL** [comment]
哦，好的，谢谢
